<?php

declare(strict_types=1);

namespace YourVendor\CrudGenerator\Tests;

use Orchestra\Testbench\TestCase as OrchestraTestCase;
use YourVendor\CrudGenerator\CrudGeneratorServiceProvider;

/**
 * Base test case for the CRUD Generator package.
 *
 * Uses Orchestra Testbench to bootstrap a minimal Laravel application
 * so that Artisan commands, config helpers, and file-system helpers
 * all work exactly as they would inside a real Laravel project.
 */
abstract class TestCase extends OrchestraTestCase
{
    /**
     * Register the package's service provider.
     *
     * @param  \Illuminate\Foundation\Application  $app
     * @return array<int, class-string>
     */
    protected function getPackageProviders($app): array
    {
        return [
            CrudGeneratorServiceProvider::class,
        ];
    }

    /**
     * Define environment setup for tests.
     *
     * @param  \Illuminate\Foundation\Application  $app
     */
    protected function defineEnvironment($app): void
    {
        $app['config']->set('crud-generator.namespace', 'App');
        $app['config']->set('crud-generator.css_framework', 'tailwind');
        $app['config']->set('crud-generator.per_page', 15);
        $app['config']->set('crud-generator.route_middleware', ['web']);
        $app['config']->set('crud-generator.paths', [
            'controller' => 'app/Http/Controllers',
            'request'    => 'app/Http/Requests',
            'rule'       => 'app/Rules',
            'service'    => 'app/Services',
            'model'      => 'app/Models',
            'migration'  => 'database/migrations',
            'views'      => 'resources/views',
            'routes'     => 'routes',
        ]);
    }

    /**
     * Delete all files generated by a test so they don't bleed across runs.
     *
     * @param  string[]  $paths  Absolute file paths to delete
     */
    protected function cleanupGeneratedFiles(array $paths): void
    {
        foreach ($paths as $path) {
            if (file_exists($path)) {
                unlink($path);
            }

            // Remove empty parent directories (best-effort)
            $dir = dirname($path);
            if (is_dir($dir) && count(scandir($dir)) === 2) {
                rmdir($dir);
            }
        }
    }
}
